name: Publish to Test PyPI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2 
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install setuptools==46.* wheel==0.34.*

      - name: Build
        run: python setup.py bdist_wheel

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
